name: "Release candidate"

on:
  push:
    tags: # run when non-official semver tag has been introduced (release candidates etc)
      - "v[0-9]+.[0-9]+.[0-9]+-*"

env:
  go_version: "^1.20"

jobs:
  build-test:
    name: "Build & test"

    uses: ./.github/workflows/build-test.yaml

  release-candidate:
    name: "Release candidate"

    needs: build-test

    runs-on: "ubuntu-latest"

    steps:

    - name: "Checkout"
      uses: actions/checkout@v3

    - name: Download binaries
      uses: actions/download-artifact@v3
      with:
        path: dist

    - name: "Release"
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: true
        files: |
          LICENSE
          dist/*/*
